### ISSUE TITLE
Can we get a compiled binary?

### ISSUE THREAD

**Issue by davidmanheim** [blackkeyboard/zgenerate#3]

**Comment by blackkeyboard** [comment]
@davidmanheim for which platforms would you be interested in?

I'm generally not keen to supply binaries but I can provide them with the usual warnings

**Comment by blackkeyboard** [comment]
I'm closing this issue assuming you meant Windows binaries

https://github.com/blackkeyboard/zgenerate/releases/tag/v1.0.0
