### ISSUE TITLE
Importing pivate key with zcash-cli gives: "Invalid private key encoding"

### ISSUE THREAD

**Issue by titusz** [blackkeyboard/zgenerate#4]

**Comment by blackkeyboard** [comment]
Fixed in https://github.com/blackkeyboard/zgenerate/commit/3ebb3058f40e28a6ecf94195c695105f4ee9cf5d

**Comment by titusz** [comment]
Is there any way to recover the balance on mainnet from an address that was generated before the bug fix?

**Comment by blackkeyboard** [comment]
Yes, if you have kept the passphrase follow the upgrade instructions and run

`zretrieve -passphrase="put_passphrase_here"`

The mainnet private key will be displayed

**Comment by titusz** [comment]
thanks... that did the trick :)
